### ISSUE TITLE
Fix "Correct" values

### ISSUE THREAD

**Issue by jeajones** [RUGSoftEng/2017-Cognitive-Sensors#111]
I'm fairly sure the values in the column called "correct" aren't right.

**Comment by aukeroorda** [comment]
I'm not able to reproduce incorrect results. Maybe the apk is generated from an older version? I have the feature-graphdata version. I think it was fixed in commit https://github.com/RUGSoftEng/2017-Cognitive-Sensors/commit/09d6a681448f46bb61aba6d539ca854886bb4d67

**Comment by jeajones** [comment]
Just tested them, they seem to be working now, good stuff.
