### ISSUE TITLE
Process Game Usage Data for Eventual Graphing

### ISSUE THREAD

**Issue by spina-a-d** [RUGSoftEng/2017-Cognitive-Sensors#47]

**Comment by jakedavison** [comment]
Front-end display assets have been created. My next step will be to get this functionality ready to receive processed game data. This should be discussed at the next meeting.

**Comment by jakedavison** [comment]
Okay, it's almost ready to take the data. It's worth taking a look at doing that know, the methods are all there. I do need to set up an interface to communicate between activity and the fragments until it will work.

**Comment by jakedavison** [comment]
Now all that needs handling is fetching the data and creating the graphs. The methods for this appear in the Feedback activity class as todos.

**Comment by jeajones** [comment]
The data for the graphs should be available from the graphdata class, the feature-graphdata branch has the latest version and hopefully is working properly, if not let me know. I've done some testing but new issues might come up when trying to graph it.
