### ISSUE TITLE
Update ReadMe with Feedback

### ISSUE THREAD

**Issue by spina-a-d** [RUGSoftEng/2017-Cognitive-Sensors#49]
We were left feedback on the readme to make it even more simple for someone.

**Comment by spina-a-d** [comment]
Links required for:
-Configuring Virtual Phone in Android Studio
-Turning Developer Mode on in Android
-Updating Android Studio

Explain where to put URL for the API.

**Comment by spina-a-d** [comment]
just the URL part left @ThomasdenH

**Comment by jeajones** [comment]
Added an explanation of where to put the URL, although I think it would be better to move it to values
