### ISSUE TITLE
Query Local Database for Data to be processed into a chart.

### ISSUE THREAD

**Issue by spina-a-d** [RUGSoftEng/2017-Cognitive-Sensors#50]
As it says.  Need to query SQLite to generate charts.

**Comment by jeajones** [comment]
The data can be processed from the class "Graphdata". Two of the queries are currently difficult to do as it requires the QuestionID, something that isn't being stored correctly at the moment, more details about that issue in issue #56. Also a better way to gather this data can be seen in issue #57.

**Comment by jeajones** [comment]
Should be working properly once issue #56 is working properly.
