### ISSUE TITLE
Leave Comments about Testing Here.

### ISSUE THREAD

**Issue by spina-a-d** [RUGSoftEng/2017-Cognitive-Sensors#51]
Looking for ideas about testing our software.  Leave Comments and Ideas here.

**Comment by ThomasdenH** [comment]
Testing whether the app will build is fairly straigtforward with for example Travis CI, see [here](https://docs.travis-ci.com/user/languages/android/).

If we want to do more thorough testing, we should create unit tests and use the [Android testing framework](https://developer.android.com/studio/test/index.html). This would be good and can be as complex as we like, but is more work to set up.

**Comment by spina-a-d** [comment]
@ThomasdenH I think we should do the thing with Android Testing Framework.  If everyone is in agreeance please make an Issue about it and we'll assign someone to it for next iteration.

**Comment by ThomasdenH** [comment]
I think we should not do this for the entire app. As we fix bugs and make small improvements it might make sense to make test cases for them, but I don't think full test coverage is in scope.

**Comment by ThomasdenH** [comment]
Closing this, as there has not been any discussion in the last days. Please reopen if you disagree.
