### ISSUE TITLE
Update Docs with Feedback on Iteration 4 of Deliverables

### ISSUE THREAD

**Issue by spina-a-d** [RUGSoftEng/2017-Cognitive-Sensors#52]

**Comment by jeajones** [comment]
I've updated the docs, the requirements doc still needs changes. I've addressed all of Peter's comments on the architecture doc, but there may be new things we want to mention in it, such as the new feedback window.

**Comment by canismayorisxl** [comment]
Il do the req doc today

Op 15 mei 2017 03:38 schreef "jeajones" <notifications@github.com>:

**Comment by ThomasdenH** [comment]
I went over the requirements document and made some tiny changes. I think it looks OK.

**Comment by jeajones** [comment]
@ThomasdenH make sure to update the change log when you edit the requirements doc

**Comment by ThomasdenH** [comment]
@jeajones I wasn't sure whether I should do it since the changes were so minimal, but I will.

**Comment by ThomasdenH** [comment]
I think everything has been addressed now.
