### ISSUE TITLE
Upload to Google Play Store

### ISSUE THREAD

**Issue by ThomasdenH** [RUGSoftEng/2017-Cognitive-Sensors#54]
To upload the app to the Play store, we need to do some things.

- [x] Pay the fee of $25. (We should ask the customer)
- [x] Create screenshots for different screen sizes (phone, tablet)
- [x] Create store images (high res icon, store background)
- [x] Create a signed version of the app and upload
- [x] Distribute as a bèta version (?)

**Comment by spina-a-d** [comment]
Has someone started this process or should I do so?

**Comment by ThomasdenH** [comment]
I have created an account already. Really the payment is the only thing blocking this.

**Comment by jeajones** [comment]
I think she told us to pay and give her the receipt for reimbursement. @JakeDavison you have the email?

**Comment by jakedavison** [comment]
Hi Jake,
I talked to our secretary, Elina Sietsema, and you can just go ahead and get the Playstore developer’s license. Make sure you get a receipt, and then Elina can help to get you reimbursed.
Warm regards,
Marieke

**Comment by ThomasdenH** [comment]
Has anyone got a credit card?

**Comment by ThomasdenH** [comment]
I have given the details to @ZamirAmiri, he will handle the payment.

**Comment by jakedavison** [comment]
How is this going?

**Comment by canismayorisxl** [comment]
thomas was not reachable this weekend, we are planning to buy the account tomorrow  after the meeting.

**Comment by ThomasdenH** [comment]
We need to have:

- [x] A high resolution icon (512x512)
- [x] A feature graphic (1024x500, this is the image on the top of the store page)
- [x] A published and signed APK file
- [x] Content rating (Can only be completed after APK upload)

**Comment by JakeDavison** [comment]
I'll work on these

**Comment by jakedavison** [comment]
I've created a folder in the files section of basecamp with the requested graphics.

**Comment by ThomasdenH** [comment]
Thank you. I have updated the listing. The only thing to do is create a signed APK.

**Comment by ThomasdenH** [comment]
I have finished this. The app is currently pending publication, this shouldn't take too long. The app have been beta-released, which means that it will only be visible to users who have opted-in to test.
