### ISSUE TITLE
Update Database with QuestionAnswerID

### ISSUE THREAD

**Issue by jeajones** [RUGSoftEng/2017-Cognitive-Sensors#56]
The QuestionAnswers need to have the correct questionID stored. This isn't happening at the moment because the QuestionAnswers don't currently have a unique identifier due to an oversight in the ORM design. Adding a QuestionAnswerID column to the database should fix this issue.

**Comment by jeajones** [comment]
Although a new column has been added, I don't think it has fixed the issue completely as questionAnswers still have incremented questionIDs

**Comment by aukeroorda** [comment]
The QuestionId column seems to be fixed. Adding a primary key with autoincrement should fix this issue.
