### ISSUE TITLE
Alter which questions are asked depending on previous answers.

### ISSUE THREAD

**Issue by jeajones** [RUGSoftEng/2017-Cognitive-Sensors#72]
Currently we have three questions:

1. What were you just thinking about?
2. How difficult was it to disengage from the thought?
3. What was the valence of your recent thought?

If you answer that you were on task in question 1, the other questions don't make much sense.
We need to change the app so the other questions are or aren't displayed depending on the previous answers.

**Comment by ThomasdenH** [comment]
I'll see if I can find a nice way to send this data with the questions from thw Google sheet.

**Comment by spina-a-d** [comment]
@ThomasdenH  did you end up doing this, I think at the meeting you said you would?

**Comment by ThomasdenH** [comment]
I don't think I will make the deadline, but yes, I am doing this.

**Comment by ThomasdenH** [comment]
Now the question order can be edited in a way that makes sense. This can be done in the database.

**Comment by spina-a-d** [comment]
Can we close this as done?

**Comment by ThomasdenH** [comment]
Yes.
