### ISSUE TITLE
Game does not terminate if no action is taken

### ISSUE THREAD

**Issue by canismayorisxl** [RUGSoftEng/2017-Cognitive-Sensors#73]
If you don't tap on the screen even once , except for when the questions pop up. The game wont terminate.
How ever if after a while the screen is tapped even once it will terminate. The problem how ever is that the game with 30 minutes of data then will be sent to the sheet which results in bad data.

**Comment by spina-a-d** [comment]
@ZamirAmiri do you think the game should just cut-off when the timelimit is reached, regardless of what the player is doing?

**Comment by canismayorisxl** [comment]
How about a timer that keeps track when the last tine an input was given and then if timer > 5min  terminate game.

**Comment by canismayorisxl** [comment]
Since the game gets stuck at the form window when the player has not performed any action, we can ignore this issue for now and only look at it if the all the other issues have been resolved.

**Comment by jakedavison** [comment]
Game now terminates without saving data after 10 consecutive numbers not clicked.
