### ISSUE TITLE
Data from unfinished games

### ISSUE THREAD

**Issue by canismayorisxl** [RUGSoftEng/2017-Cognitive-Sensors#74]
The game sends also data from unfinished game sessions if the game session has not been completely finished, resulting in bad data.

**Comment by jeajones** [comment]
What makes the data bad? Is it corrupted? I think we still want to collect data from games if the player didn't play until the end.

**Comment by canismayorisxl** [comment]
even if he played the game for 1 sec?

**Comment by spina-a-d** [comment]
I think this is something the customer should be asked.

**Comment by jeajones** [comment]
Maybe, the customer wanted minimal processing of the data before we made it available. I think we carry on uploading it and the customer can filter it out herself if she wants.
Although it doesn't hurt to ask.

**Comment by jeajones** [comment]
Just spoke to the customer about this, she wanted all data to be saved. So it is fine as it is.

**Comment by ThomasdenH** [comment]
Great!
