### ISSUE TITLE
Notification Frequency

### ISSUE THREAD

**Issue by canismayorisxl** [RUGSoftEng/2017-Cognitive-Sensors#75]
I  only tested the daily and never options.
Daily works fine but the never function does not. It keeps sending you a notification every day regardless.

**Comment by spina-a-d** [comment]
This is weird, I had thought I had successfully made it remove pending notifications when never was clicked.  when we added the slider.  It'll have to be looked at again.

**Comment by canismayorisxl** [comment]
I will fix this issue today/tomorrow

**Comment by canismayorisxl** [comment]
/**
     * This method sets a daily alarm for a certain time
     * //TODO:: right now we use a default, we might wanna change this if we ever give optional times
     */
    public void setUpNotifications(int currentSetting) {
        if(currentSetting == -1){
            Calendar calendar = Calendar.getInstance();
            calendar.setTimeInMillis(System.currentTimeMillis());
            calendar.set(Calendar.HOUR_OF_DAY, 10);
            calendar.set(Calendar.MINUTE, 30);
            calendar.set(Calendar.SECOND, 0);

            Intent alarmIntent = new Intent(this, MyReceiver.class);
            PendingIntent pendingIntent = PendingIntent.getBroadcast(this, 0, alarmIntent, 0);
            AlarmManager alarmManager = (AlarmManager) getSystemService(Context.ALARM_SERVICE);
            alarmManager.setRepeating(AlarmManager.RTC_WAKEUP, calendar.getTimeInMillis(), AlarmManager.INTERVAL_DAY, pendingIntent);
        }
    }

**Comment by canismayorisxl** [comment]
Thats where the problem is
the game has only a default setting for the notification

**Comment by canismayorisxl** [comment]
@a-d-spina-student  I think it should be a lot easier for you to change the code then it would be for me as im not suure what every variable is etc. But if you dont have time then i can try changing it aswell.

**Comment by canismayorisxl** [comment]
In options.java The last case can be changed to:
alarmManager.setRepeating(AlarmManager.RTC_WAKEUP, calendar.getTimeInMillis(), AlarmManager.INTERVAL_DAY * 0, pendingIntent);
to make it work.
My pc wont run the program for some reason so would be nice if someone could check that.


switch (sb.getProgress()) {
            case 1:
                alarmManager.setRepeating(AlarmManager.RTC_WAKEUP, calendar.getTimeInMillis(), AlarmManager.INTERVAL_DAY, pendingIntent);
                break;
            case 2:
                alarmManager.setRepeating(AlarmManager.RTC_WAKEUP, calendar.getTimeInMillis(), AlarmManager.INTERVAL_DAY * 7, pendingIntent);
                break;
            default:
                break;
        }

**Comment by canismayorisxl** [comment]
nvm lol that is wrong instead of 0 using a larger number would do the trick though

**Comment by spina-a-d** [comment]
@ZamirAmiri in "feature-notifications" I've been working and seem to have fixed it.  I don't know how to test it, but before the notification I was trying to cancel was not the same as the ones that were scheduled.  They now return true when I test if they are the same so they should be being removed.  If you can figure out how to test this is true let me know. (I have not pushed yet).

**Comment by canismayorisxl** [comment]
@a-d-spina-student Im not sure about the testing part but what definitely could work is to set the default frequency to never and keep the rest of the code the same . Or change in the option.java the default case in : 
switch (sb.getProgress()) {
case 1:
alarmManager.setRepeating(AlarmManager.RTC_WAKEUP, calendar.getTimeInMillis(), AlarmManager.INTERVAL_DAY, pendingIntent);
break;
case 2:
alarmManager.setRepeating(AlarmManager.RTC_WAKEUP, calendar.getTimeInMillis(), AlarmManager.INTERVAL_DAY * 7, pendingIntent);
break;
default:
break;
}

to some value that is so large so that the notification does not appear for the next one year creating the illusion of never.

**Comment by canismayorisxl** [comment]
but if you are sure that you have solved it then i think we can close the issue

**Comment by spina-a-d** [comment]
@ZamirAmiri I'd prefer not to hack it to a fix, but that might be necessary if we still discover issues.  For now I think its fixed and we can mark it resolved.
