### ISSUE TITLE
Landscape mode.

### ISSUE THREAD

**Issue by canismayorisxl** [RUGSoftEng/2017-Cognitive-Sensors#76]
If the phone is turned to landscape mode, the UI becomes messy. Since there is no reason for the app to have a landscape mode, i suggest we remove that functionality all together.

**Comment by ThomasdenH** [comment]
Please note that this also means the app will become less usable on tablets. In general I think it is a good idea to support as much devices as possible unless there's a good reason to drop them.

**Comment by spina-a-d** [comment]
Or we just add landscape modes, that might not be too difficult?

**Comment by jakedavison** [comment]
I think it'll be best to just lock the orientation, I'll find out how to do this.

**Comment by ThomasdenH** [comment]
See [this](https://stackoverflow.com/questions/4675750/lock-screen-orientation-android).

**Comment by jakedavison** [comment]
Thanks, Thomas. I'll do this today.

**Comment by ThomasdenH** [comment]
I have made a pull request for this, it just needs to be merged.

**Comment by spina-a-d** [comment]
I've merged it, can we close this?

**Comment by ThomasdenH** [comment]
Yes.
