### ISSUE TITLE
Begin New Presentation Preparation

### ISSUE THREAD

**Issue by spina-a-d** [RUGSoftEng/2017-Cognitive-Sensors#81]
I need two volunteers to start making the modified slides for the final presentation.  We'll also need two volunteers to present (can overlap with the people making the slides obviously), but its good to be prepared and not worry last minute about it.

**Comment by spina-a-d** [comment]
- Your development process
- - How did you plan/structure/evaluate the development?
- The communication within your team
- The communication with the customer
- The 3 best practices that you used in your team
 - - Regarding e.g. code review, conflict solving, quality controls
- Your technology stack and how you set up your project
 - - e.g. did you deploy a web server, an App to the AppStore/Google Play Store
 - - did you use continuous integration and/or a build server?
- Lessons learned during development
- The architectural structure of your project (Visuals are highly appreciated here!!)
- The most elegant design aspect of your code
 - - i.e. which is your most elegant solution to a coding problem you had?

**Comment by spina-a-d** [comment]
@LorenaArquero , @ZamirAmiri would you consider working on this stuff?

**Comment by LorenaArquero** [comment]
Yes for me is no problem to do the slides. But I'm a terrible public speaker so I will prefer to not do the presentation part if possible.

**Comment by canismayorisxl** [comment]
I already offered making the slides but i aswel suck at presenting stuff

Op 31 mei 2017 19:22 schreef "LorenaArquero" <notifications@github.com>:

**Comment by spina-a-d** [comment]
What's the status on this?

**Comment by canismayorisxl** [comment]
Havent started to work on it yet. I have been busy this week.  I can start working on it Friday evening though. When is the presentation given again? I cant seem to find it on nestor.

**Comment by spina-a-d** [comment]
The presentation is on 16/06/2017.  But, I'd like the first iteration of the presentation done for this Monday so @PJUllrich  and the other staff members have time to review it and recommend changes.  Then The presenters will need to practice with the final copy.  So I think the first copy should definitely be done by 12/06/2017.

**Comment by canismayorisxl** [comment]
Yeah no worries theb i can work on it the whole weekend

Op 6 jun. 2017 16:22 schreef "A D Spina" <notifications@github.com>:

**Comment by spina-a-d** [comment]
Thanks @ZamirAmiri, also, @ZamirAmiri, @ThomasdenH , @jeajones , @JakeDavison , @aukeroorda , @LorenaArquero.  @ThomasdenH has indicated that he doesn't want to do the presentation this time.  Since everyone has been quite reluctant to do it, I can obviously do it again, but we need someone to replace @ThomasdenH .  Please volunteer yourself for this role ASAP.

**Comment by jakedavison** [comment]
I can present but because of some personal circumstances at the moment I'd rather not do it if possible. If nobody else can do it, I will do it.
