### ISSUE TITLE
Sending PlayerIDs to a Google doc

### ISSUE THREAD

**Issue by jeajones** [RUGSoftEng/2017-Cognitive-Sensors#86]
The customer wants to use a google doc to make the questionnaire (U-1 in the requirements doc) and she wants to be able to link a user's questionnaire responses to their play data. To do this we should be able to send a player's unique ID to the questionnaire sheet.

**Comment by ThomasdenH** [comment]
I have no idea how to do this. Maybe we just need to show it to the user and let them input it in the form.

**Comment by spina-a-d** [comment]
@ThomasdenH @jeajones yeah we'll probably have to show it to them to have them copy paste it.  Have we made any progress on this?

**Comment by jakedavison** [comment]
If we know how we are going to do this I can implement the correct screen in the app that shows the ID and links to the form.
