### ISSUE TITLE
Indicator for on-task, off-task questions. 

### ISSUE THREAD

**Issue by jeajones** [RUGSoftEng/2017-Cognitive-Sensors#89]
Currently only questionID = 0 indicates whether or not a person is on task depending on their answers to the multiple choice questions. As we're trying to make the questions dynamic this makes little sense. To add this functionality we need to:

1.  Add a new column to the Google Sheet to indicate on/off task
2.  Change the local database to download this information and store it
3.  Change graphData to retrieve data based on these new columns

**Comment by jakedavison** [comment]
I'm waiting on this so that I can fix the formatting of the bar charts.

**Comment by aukeroorda** [comment]
I'll work on this tomorrow and see if I can fix this.

**Comment by aukeroorda** [comment]
I've implemented this on the client-side, and added some columns to the wander sheet which are required to define this information. Can someone from the server edit the script so that it sends the two new columns from the questions table? The names for the fields are in the column titles.

**Comment by ThomasdenH** [comment]
@jeajones ones finished this yesterday. Is this working now, @aukeroorda?

**Comment by jakedavison** [comment]
To clarify, all that is needed for the two bar charts is the average response time and accuracy for before answering on task and off task.
So GraphData should either be able to calculate and pass those four values or pass an array of all response times and accuraccies (split by on and off task)  and the avg can be calculated from that.

**Comment by aukeroorda** [comment]
I'll check if it is working and update the function in graphData to retrieve these values.
