### ISSUE TITLE
Ensure correctness of graph data

### ISSUE THREAD

**Issue by jakedavison** [RUGSoftEng/2017-Cognitive-Sensors#91]
Some of the data from the database (like avg response time) isn't correct.

**Comment by jeajones** [comment]
![image](https://user-images.githubusercontent.com/21986957/26949229-68f6b346-4c99-11e7-9eb2-0cf5b5a93ae5.png)
Just did a little testing on this, looks like some response times are being saved as negatives. This needs fixing @aukeroorda @LorenaArquero

**Comment by jakedavison** [comment]
Yeah, some new testing of mine finds that it usually works fine now but negative values are possible. If we don't save incomplete sessions, this may solve it. If we don't do that, we'll probably have to set a db boolean for complete and then ChartData can ignore incomplete sessions.
