### ISSUE TITLE
Update Documents

### ISSUE THREAD

**Issue by jeajones** [RUGSoftEng/2017-Cognitive-Sensors#92]
Architecture document need the ORM model updating @ThomasdenH (it currently still says that a questionID + gamesession is unique, plus we may need to add in whether or not a question indicates on-task or off-task).

Requirements document needs to include all comments from Peter from the last iteration.

**Comment by ThomasdenH** [comment]
I have changed some things in the requirements document, it still needs work.

**Comment by ThomasdenH** [comment]
I have updated the diagrams in the Architecture document as well.

**Comment by ThomasdenH** [comment]
The references in the requirements document are now fixed as well.
