### ISSUE TITLE
Quitting a Game Early Causes the Function getAvg() to divide by zero in GameSession.java

### ISSUE THREAD

**Issue by spina-a-d** [RUGSoftEng/2017-Cognitive-Sensors#95]
@aukeroorda @LorenaArquero @jeajones @JakeDavison .  Has this been fixed in newer branches or is this still an issue?

**Comment by jakedavison** [comment]
I don't know. We have a way of not saving games when you quit so we could
implement that once we don't need to save short games for testing.

**Comment by spina-a-d** [comment]
It looks like a function @jeajones made 17 days ago

**Comment by aukeroorda** [comment]
This has been fixed in feature-graphdata
